### ISSUE TITLE
스타일 가이드

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#12]
기본 사이트 스타일/CSS
메인 컬러, button, 링크 등등

cc. https://nonidesign.tistory.com/11
@post50

**Comment by post50** [comment]
dev / css branch 생성

**Comment by post50** [comment]
styleguide 1차 완성
![image](https://github.com/seeoya/bapbaksa/assets/76762877/f97f92eb-f246-4f60-a962-48740aebf4cc)
![image](https://github.com/seeoya/bapbaksa/assets/76762877/45c6e6ed-4f45-4e7b-977a-ed1c1b4e3003)
![image](https://github.com/seeoya/bapbaksa/assets/76762877/93438222-3b03-447e-8c85-6da44196b85b)

**Comment by post50** [comment]
![image](https://github.com/seeoya/bapbaksa/assets/76762877/6a76f8ee-8926-45ea-ac24-5ac67857272b)

styleguide 2차

**Comment by post50** [comment]
![image](https://github.com/seeoya/bapbaksa/assets/76762877/df427295-4188-4fd5-ac41-e42504b095b2)

styleguide 2차

**Comment by post50** [comment]
![image](https://github.com/seeoya/bapbaksa/assets/76762877/3dac5c9f-d747-4af7-91eb-1105083a39c3)
![image](https://github.com/seeoya/bapbaksa/assets/76762877/94621d79-4f18-4590-9304-5f32543fcb4f)
스타일 가이드 업데이트

**Comment by seeoya** [comment]
240429 코드리뷰 요약

- [x] light/dark 컬러들 가운데 색상과 비슷하게
- [x] 버튼/input 스타일 등 둥글기 체크 (각지게 or 더 동그랗게)
- [x] Nav 버튼 스타일 재검토 (배경색/글자색/둥글기 등)
- [x] 하이라이트 컬러 사용처 검토

@post50

**Comment by post50** [comment]
light/dark 컬러들 가운데 색상과 비슷하게

![image](https://github.com/seeoya/bapbaksa/assets/76762877/2627123f-afe6-4610-98fe-318d1e0ee496)

 버튼/input 스타일 등 둥글기 체크 (각지게 or 더 동그랗게)
![image](https://github.com/seeoya/bapbaksa/assets/76762877/55b058e2-5914-477c-b4bb-0ae55581a3f3)

 하이라이트 컬러 사용처 검토(red만 남김)

**Comment by post50** [comment]
Nav 버튼 스타일 재검토 (배경색/글자색/둥글기 등)
![image](https://github.com/seeoya/bapbaksa/assets/76762877/2fddbfa7-a80a-4ce0-8413-3c9d658c6b27)
(hover시 색상 변함)

https://github.com/seeoya/bapbaksa/blob/css/client/src/css/style.css

**Comment by seeoya** [comment]
> light/dark 컬러들 가운데 색상과 비슷하게
> 
> ![image](https://private-user-images.githubusercontent.com/76762877/326646735-2627123f-afe6-4610-98fe-318d1e0ee496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Njg1ODIsIm5iZiI6MTcxNDQ2ODI4MiwicGF0aCI6Ii83Njc2Mjg3Ny8zMjY2NDY3MzUtMjYyNzEyM2YtYWZlNi00NjEwLTk4ZmUtMzE4ZDFlMGVlNDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5MTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOGRjMWNkNjJiZDBhMTVmZDAxN2Y3YTk5YTRjYjE4ODlkMWQ4YzNlNTI1NTU0YWIwOGU2MmFhOTRlZGQ0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.quG32KqpH620xUDGhFGo3qII0apW2UBLVkfQp84S_xs)
> 
> 버튼/input 스타일 등 둥글기 체크 (각지게 or 더 동그랗게) ![image](https://private-user-images.githubusercontent.com/76762877/326646908-55b058e2-5914-477c-b4bb-0ae55581a3f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Njg1ODIsIm5iZiI6MTcxNDQ2ODI4MiwicGF0aCI6Ii83Njc2Mjg3Ny8zMjY2NDY5MDgtNTViMDU4ZTItNTkxNC00NzdjLWI0YmItMGFlNTU1ODFhM2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5MTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MmY1YTUxOGRmYzJjYTI5MDhiODg0OTMwNGEwMDY2NjJjYTliYWE0OGM1OGVlNjk5ODI4N2FkNTgzY2ViZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aWMS5v59FDaLL60GSpTPplCAkLJn3zOeS7BnKS25DSc)
> 
> 하이라이트 컬러 사용처 검토(red만 남김)

색 훨씬 보기 편하고 좋은 거 같아요 👍
메인 다크가 좀 쨍한거같은데 채도만 조금 낮춰볼 수 있을까요?
gray도 조금 더 어두운 그레이 하나 있으면 좋을 거 같은데 추가해주실 수 있을까요?

@post50
