### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#13]

**Comment by seeoya** [comment]
@Hanbiman 이슈 할당
작업 들어가기 전에 
메인 페이지에 들어갔으면 하는 내용이랑 와이어프레임(아주 간단하게) 남겨주세요

**Comment by Hanbiman** [comment]
### 레시피 홈 와이어 프레임
![레시피 홈 와이어 프레임](https://github.com/seeoya/bapbaksa/assets/124786473/db19037c-3b2f-4dec-a055-70853712a29b)

**Comment by seeoya** [comment]
https://github.com/seeoya/bapbaksa/issues/45

**Comment by Hanbiman** [comment]
### 마켓 홈 와이어 프레임
![마켓 홈 와이어 프레임](https://github.com/seeoya/bapbaksa/assets/124786473/6da71e61-dbf2-445a-ab46-448ef65aac32)
