### ISSUE TITLE
정규식 유효성 검사, 다음 API 추가

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#14]
회원가입/로그인/정보수정 시 정규식 유효성 검사 추가

**Comment by post50** [comment]
##정규식 유효성 검사 추가
signup, signin, modify
- 아이디 중복검사
- 아이디 6~20자 영문 소문자, 숫자 조합
- 비밀번호 8~20자 영문, 숫자, 특수문자 조합
- 비밀번호 재확인
- 이메일 형식 유효성 검사
- 전화번호 (000-0000-0000) 형식 유효성 검사
  
##다음 API 추가
- 주소 입력창에 아이콘 생성 후 다음 API 추가

#14

**Comment by post50** [comment]
###로그인시 엔터키로 submit()
