### ISSUE TITLE
Rset 서버 구축

### ISSUE THREAD

**Issue by Hanbiman** [seeoya/bapbaksa#29]
Rset 서버 구축

**Comment by seeoya** [comment]
데이터 return type: json

배열 X 객체 O

{
    1: {
       no: 1,
       name: "사과"
    },
    2: {
       no: 1,
       name: "사과"
    }
}

이런 형식으로 return 형식 맞춰주세여
@Hanbiman

**Comment by Hanbiman** [comment]
## 레시피 - rest 요청

순서: 3 > 2 파라미터 형식 알려주기 > 2 서치/카테고리/정렬/페이지 처리 > 2 재료필터

1. 전체 냉장고 재료


2. 리스트 - 레시피 (검색어, 필터-재료 => [no, no, ...] /카테 => [no, no, ... ], )
let 파라미터 = {
   v  search: "",
   v  재료필터: [111, 818],
   v  재료 필터 기준: 전부 포함 or 하나라도 포함 // 

   v  카테고리필터: [3, 11, 110] 하나라도 포함 (고정)
WHERE CATE = 3 OR CATE = 11 OR CATE = 110

   v  정렬: "new", "old", "시간이 긴 순서", "..." or 0/1/2/3/4...,
   v  페이지: 2
   v  페이지당 보이는 갯수 : 20개   ===> 21~40
}

서치&정렬 > result > 가공을 해서 필터링 한번 더 돌려 > 마지막에 페이징

조건 :5개 

if() 필터링 => query로 할 수 있으면 하고 (DB 갔다오기전에)
SELECT ORDER BY // LIKE = > query
if(필터가 있으면){ result => 가공 }

return json (5개 항목이 모두 확인된)



3. 리스트 - 뷰 (NO를 보내면 NO번째 리스트 json)



4. url은 한번에 처리
ex)
/recipe => 리스트(파라미터 따라 조건 처리된) 리턴
/recipe/1 => 1번째 레시피 리턴


@seeoya
