### ISSUE TITLE
REST 통신 에러 문제

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#30]
## 문제 
AWS REST 서버로 요청했을 때, json이 return 되지 않음

## 확인된 사항
1. 같은 URL로 브라우저 접속했을 땐 json이 잘 표시됨 
![image](https://github.com/seeoya/bapbaksa/assets/54855563/55957a2d-fef0-492a-80aa-f0ca9a1ceba8)
2. axios를 이용한 통신에서 발생한 문제,
axios 코드 ↓ (아래쪽 localhost 3001은 서버쪽에서 테스트한 건데 이쪽도 같은 오류)
```javascript
    const callingAxios = () => {
        axios.get("http://52.62.249.221:3002/test")
        // axios.get("http://localhost:3001/test")
            .then((result) => {
                console.log("result", result);
            }).catch(error => {
                console.log("error", error)
            })
    }
``` 
3. 브라우저 콘솔 상의 에러 로그 ↓
![image](https://github.com/seeoya/bapbaksa/assets/54855563/a2127e2f-c692-459d-9877-37050c83c516)

CORS나 PROXY 관련 문제인 거 같은데, 에러로그 검색해서 react proxy 세팅 해보려고 했는데 잘 안 됐어요.
react 설정 문제인지/rest 서버에서 json 보내줄 때 설정이 필요한지/aws 설정 문제인지 체크 부탁드립니다.

@Hanbiman

**Comment by seeoya** [comment]
## 추가 확인 사항

- [x] REST 서버 인바운드 3000, 3002, 3306 열여뒀음
- [x] RDS 서버 인바운드/아웃바운드 3000 열어뒀음
- [x] REACT 서버 인바운드 3000, 3001, 3002 열어뒀음

fetch 함수나 localhost(노드 3001) 서버로 자체적로 요청해도 마찬가지인걸 보면 react쪽에서 설정해야 할듯

**Comment by seeoya** [comment]
같은 문제 node(서비스) 서버에서도 발생하니 같이 해결해야할듯

**Comment by Hanbiman** [comment]
Cors 에러 해결 방법은 프론트엔드, 백엔드 모두 설정해야 한다.

## 프론트엔드 (현재 React) 설정

1. 해당 디렉토리로 이동 후 ```npm i http-proxy-middleware```
2. ".env.development"와 ".env.production" 생성 후 "REACT_APP_"을 꼭 앞에 붙여 작성한다. (개발 단계와 배포 단계를 오갈 때 ip주소와 파일 경로를 매번 바꿔주는 것은 비효율적이기 때문이다) (ex : ip주소, 파일 경로 등 각종 설정들) (빈칸없이 작성해야된다.)
```env:.env.development
REACT_APP_SERVER_URL=http://localhost:3002
```
3. src 폴더에 setProxy.js 생성 후
```js:setProxy.js
const { createProxyMiddleware } = require("http-proxy-middleware");

module.exports = function (app) {
    app.use(
    createProxyMiddleware("*", {
      target: process.env.REACT_APP_SERVER_URL,     // reacr server
        changeOrigin: true,
    })
    );
}; 
```
작성 (createProxyMiddleware에서 "*"로 작성하는 것은 좋지 못한 방법이긴 하다.)
4. App.js에서 axios 작성
```js:App.js
import axios from "axios";

// 생략

const callingAxios = () => {
        axios.get(process.env.REACT_APP_SERVER_URL)
            .then((result) => {
                console.log("result", result.data);
            }).catch(error => {
                console.log("error", error)
            })
    }

// 생략

```
## 백엔드 (현재 Express) 설정
1. 해당 디렉토리로 이동 후 ```npm i cors```
2. node 내장 모듈인 "os"을 사용하여 프론트엔드와 같이 개발 단계와 배포 단계를 오갈 때  ip주소와 파일 경로를 매번 바꿔주는 것은 비효율적이기 때문에 "os.version().includes('Windows')"와 "os.version().includes('Linux')"를 작성하여 ip 주소 변경
3. main.js 에 다음과 같이 작성
```js:main.js
const express = require("express");
const app = express();
const os = require("os");

// 생략

let origin_addr = "MY IP";
if (os.version().includes('Windows')) {
    origin_addr = 'http://localhost:3000';
}

app.use(cors({
    origin: origin_addr,
    credentials: true,
}));

// 생략

```
작업이 모두 끝난 뒤 제대로 작동하는지 확인해 보자
![react axios통신 완료](https://github.com/seeoya/bapbaksa/assets/124786473/38ef6f83-1c43-4705-8bb2-ad9801de8990)

**Comment by Hanbiman** [comment]
- [x] Client <-> Service(node) axios 통신 되는지 확인
- [x] Client <-> REST(node) axios 통신 되는지 확인

- [x] Client <-> Service <-> REST <-> Client 모두 한번에 되는지 확인 (삼각형)
