### ISSUE TITLE
continer 클래스 패딩 추가 요청

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#32]
![image](https://github.com/seeoya/bapbaksa/assets/54855563/f541d867-db9d-43df-80b6-648497611bd9)

현재 container 클래스에 좌우 패딩이 없어 창이 줄었을 때 좌우 여백이 없어지는 문제가 발생합니다. (현재 패딩 30px 0 50px)
container 클래스에 좌우 여백 추가하면 어떨까요?

+ 
![image](https://github.com/seeoya/bapbaksa/assets/54855563/aa2a4f02-5978-4948-b8b7-e66b6ad2a177)
backdrop-filter는 의도하신 코드가 맞을까요? blur는 blur(5px)과 같이 작성해야 적용됩니다!

@post50

**Comment by post50** [comment]
cotainer 좌우 padding 20px 추가했어요~

@seeoya

**Comment by seeoya** [comment]
![image](https://github.com/seeoya/bapbaksa/assets/54855563/26f52dcc-5610-41f1-80e2-5570ddf8deaf)


![image](https://github.com/seeoya/bapbaksa/assets/54855563/70281a49-69b7-48a8-b918-cfee707d83d2)

왼쪽에 붙는 냉장고 메뉴가 30px인데, 좌우 패딩 40px은  어려울까요?
@post50
