### ISSUE TITLE
redux + axios 세팅 & 사용법

### ISSUE THREAD

**Issue by post50** [seeoya/bapbaksa#33]
redux + axios 세팅

signup -> signup_confirm

테스트 완료

**Comment by post50** [comment]
#33 redux 사용법

# redux 폴더 -- actions 폴더 : 각자 필요한 action 파일 생성
                     -- reducers 폴더: 각자 필요한 reducer 파일 생성
                               => reducer.js    안의 combineReducers 에 생성한 reducer 넣어줌
             
## ex)  signup.jsx 페이지에서
#  import { useDispatch } from 'react-redux';
#  import {getSignupAction} from '../../redux/actions/user';

  dispatch(getSignupAction(formData));   // action 함수 호출(전송할 데이터)

# action/user.js

export const getSignupAction = (formData) => {
        
    return {
        type: 'USER_SIGNUP',
        data: formData,
        };
    
}

# reducer/user.js
import axios from 'axios';
import $ from 'jquery';
import {useNavigate} from 'react-router-dom';
import {SERVER_URL} from '../../util/url';


axios.defaults.withCredentials = true;



export const userReducer = (state={}, action) => {

   switch (action.type){

       case 'USER_SIGNUP':
            
            let formData = action.data;

            const request = axios({
                url: `${SERVER_URL.TARGET_URL()}/user/signup_confirm`,                
                method: 'post',      
                data: formData,
            })
            .then(res => {        
                console.log('res: ', res);
                console.log('res.data: ', res.data);
                console.log('res.affect: ', res.data.data.affectedRows);

                if (res.data !== null && res.data.data.affectedRows > 0) {
                    console.log('AXIOS SIGN_UP COMMUNICATION SUCCESS ==> ', res.data);
                    alert('회원가입에 성공하였습니다.');
                    useNavigate('/');
        
                } else {
                    alert('회원가입에 실패하였습니다.');                
                }
            })
            .catch(error => {
                console.log('AXIOS SIGN_UP COMMUNICATION ERROR');
                
            })
            .finally(data => {
                console.log('AXIOS SIGN_UP COMMUNICATION FINALLY');
        
            })

        return {...state};
        break;
      
       default:
           return state;    
   }
 
}


====> server
userRouter.js    => userService.signup_confirm
                              결과 react로 전송  res.json({data: result});


@seeoya @Hanbiman @choiheebeom

**Comment by post50** [comment]
#33
url : process.env.REACT_APP_SERVER_URL + `/api/user/signup_confirm`,

url 환경변수로 변경 -> dev push 완료
@seeoya @Hanbiman @choiheebeom

**Comment by seeoya** [comment]
## axios를 이용해 데이터를 가져온 후 state에 할당해야 할 경우
### 240503 추가

1. action을 수행하는 파일(현재 redux/actions/ 디렉토리 안의 파일들)에서 axios를 처리한 후
```javascript
export const loadMyFridgeAction = async (uNo) => {
    let list = [];

    await axios
        .get(process.env.REACT_APP_SERVER_URL + "/fridge", {
            params: {
                u_no: uNo,
            },
        })
        .then((data) => {
            data.data.map((el) => {
                list.push(el.ig_no);
            });
        })
        .catch((err) => {})

    return { type: "set_my_fridge", data: list };
};
```

2. 클라이언트(react)에서 async/awiat을 이용해  dispatch 실행
```javascript
const loadMyFridge = async () => {
        let uNo = 1;
        dispatch(await loadMyFridgeAction(uNo));
    }
```

3. state 처리는 reducer에서
```javascript
        case "set_my_fridge":
            let data = action.data;

            return { ...state, MyFridge: data };
```

@post50 @Hanbiman @choiheebeom
