### ISSUE TITLE
rest params 처리 정리

### ISSUE THREAD

**Issue by Hanbiman** [seeoya/bapbaksa#34]
## recipe params

/recipe/ => params.type = list(레시피 기본 정보), view(레시피 상세 정보), page(페이지 관련)

### recipe params.type = list

list params = {search, sort, region, time, food, foodinclu, difficult, category, page}

search => 입력된 검색어가 들어간 항목을 찾아준다.

sort => "old", "new", "lesstime", "moretime" 로 나뉜다. (난이도 추가 예정)

region => "한식", "서양", "일본", "중식", "동남아시아", "이탈리아", "퓨전" 로 나뉜다.

time => "1", "10", "20", "30", "40", "50", "60" 로 나뉜다.

food => 배열로 RECP_INGRD_CODE(int) 들어간다.

foodinclu => 0 : 선택한 항목이 하나라도 포함된 식재료, 1 : 선택한 항목이 모두 포함된 식재료

difficult => 0 : 초보 환영, 1 : 보통, 2 : 어려움

category => 배열로 RECP_CATEGORY_CODE(int)에 들어간다.

page => 1, 2, 3, 4, ... 으로 보내서 동적으로 페이지 생성

pagePerItem => 정해진 숫자만큼 limit을 정의한다. (limit = params.pagePerItem)

### recipe params.type = view

params 없이 RECP_CODE로 바로 찾게 됨

**Comment by Hanbiman** [comment]
## refrigeator params

/refrigeator/ => params.type = list(냉장고 전체), select(냉장고 선택 목록)

params ={food}

food => 선택한 RF_NO 가 내 냉장고 목록으로 들어간다. 없으면 전체 출력

**Comment by seeoya** [comment]
@Hanbiman 

- [x] time, difficult도 배열로 보낼 수 있을까요? (전부 나오게)

- [x] 파라미터에 pagePerItem도 추가해주세요. (페이지당 갯수)

**Comment by seeoya** [comment]
@Hanbiman 

- [x] sort order by limit에 조건 추가

- [x] time 제거

- [x] sql문 조건에 괄호, 괄호 사이 AND 추가

위 사항(특히 괄호) 수정 후 여러 조건 적용되는지 확인

**Comment by seeoya** [comment]
요청사항  @Hanbiman 

- [x] 리스트 돌려줄때 페이징 안 된 넘버도 받아올 수 있나요?

ex) 조건 전체 적용 후 101건 일 때
파일 json은 20개만 잘라서 그대로 / json에 `count: 101` 형식으로 전체 숫자 따로 리턴

총 nnn 건 표시용

```json
{
    "1": {},
    "2": {},
    "11": {},
    "count": 3
}
```

**Comment by Hanbiman** [comment]
sort order by limit FI 추가해야 하는 조건
### 1. foodinclu: 1, page: 0, pagePerItem: 30 일 경우
- 간장, 고춧가루 선택 시 목록 정상 출력 (74개)
- 조림 추가 시 정상 출력 (8개)
- 국 추가 시 정상 출력 (15개)
- 한식 추가 시 정상 출력 (15개)
- 한식만 출력 되어서 닭고기, 국, 구이, 튀김으로 변경 목록 정상 출력 (11개)
- 한식 추가 시 정상 출력 (4개)
- 양식 추가 시 정상 출력 (6개)
- 양식, 중식으로 변경 시 정상 출력 (4개)
- 카테고리 제거 후 '초보환영' 추가 시 정상 출력 (1개)
- '보통'으로 변경 시 정상 출력 (10개)

### 2. foodinclu: 1, page: 1, pagePerItem: 30 일 경우
- 간장, 고추장 선택 시 정상 출력 (30 + 11개)
- 밥, 국, 조림, 구이, 튀김, 찜, 나물, 밑반찬, 도시락, 찌개, 볶음 선택 시 정상 출력 (30 + 8개)
- 한식 추가 시 (30 + 3개) 정상 출력
- '초보환영', '보통' 추가 시 (30 + 5개) 정상 출력

### 3. foodinclu: 0, page: 1, pagePerItem: 30 일 경우
- 31번부터 60번까지 정상 출력
- 추가 재료 선택 시 오류 발생
- 국, 튀김 선택 시 오류 (9개가 출력되야 하지만 30개 출력)
- 양식 추가 시 정상 출력 (30 + 13개) (여러개인 경우엔 page 수를 늘려 확인 필요)
- 난이도 '어려움' 추가 시 출력 안되는 오류

**Comment by Hanbiman** [comment]
### foodinclu: 0, page: 1, pagePerItem: 30 일 경우 (1차 해결 후 테스트)

- 추가 재료 선택 시 오류 발생 => 갓, 건멸치 선택 시 정상 출력 (30 + 8)
- page = 2일 때, 국, 튀김 선택 시 오류 (9개가 출력되야 하지만 30개 출력) => 국, 튀김 선택 시 정상 출력 (60 + 9개)
- 양식 추가 시 정상 출력 (30 + 13개) (여러 개인 경우엔 page 수를 늘려 확인 필요) => page = 2일 때, 한식, 중식, 일식, 양식 선택 후 정상 출력 (60 + 3개)
- 난이도 '어려움' 추가 시 출력 안되는 오류 => 국, 튀김, 찌개, 한식, '보통' 선택 후 정상 출력 (30 + 10개)
