### ISSUE TITLE
db tbl_user 변경 테이블

### ISSUE THREAD

**Issue by post50** [seeoya/bapbaksa#35]
CREATE TABLE TBL_USER (
	u_no		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	u_id		VARCHAR(50) NOT NULL,
	u_pw		VARCHAR(200) NOT NULL,
	u_mail		VARCHAR(100) NOT NULL,
	u_phone		VARCHAR(50) NOT NULL,
	u_google_id	VARCHAR(100),
	u_status	INT NOT NULL DEFAULT 1,
    u_zip_code  VARCHAR(50),
    u_first_address VARCHAR(100),
    u_second_address VARCHAR(100),
	pi_name 	VARCHAR(200) DEFAULT "",
    u_refresh_token VARCHAR(500) DEFAULT NULL,
	u_reg_date	TIMESTAMP DEFAULT NOW(),
	u_mod_date	TIMESTAMP DEFAULT NOW()
);

@seeoya

**Comment by seeoya** [comment]
SQL문 업데이트 완료
AWS DB 서버 업데이트 완료
