### ISSUE TITLE
페이지 로그인 체크

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#39]
(전체 페이지 작업 후 일괄 처리)

로그인 하지 않으면 접속하지 못하는 페이지들(마이페이지 관련 등등) 로그인 체크 처리 추가 필요

**Comment by seeoya** [comment]
경로: client/src/util/check.js 
loginCheck() => 유저 체크 / 비로그인 시 -1 : 로그인 시 유저 status(1, 2, 999...) 반환
adminCheck() => 관리자 체크 / 관리자가 아닐 경우 -1 : 관리자일 경우 1 반환

## 사용법

```javascript
  console.log("user: ", await loginCheck());
  console.log("admin: ", await adminCheck());
// 외 분기 자유롭게 사용
```

로그인이 필요한 페이지에서 사용 가능
필요 시 useNavigate 이용해서 다른 페이지로 이동시킬 것 (location XXX) 

@post50 @Hanbiman @choiheebeom

**Comment by seeoya** [comment]
확인 필요한 페이지

### 회원
- [ ] 정지 회원일 경우 사용 불가 처리 => 로그아웃 처리 or 부분 기능만 허용
- [ ] 마이페이지 => 로그인 페이지로 이동
- [ ] 레시피 좋아요 => 로그인 페이지로 이동
- [ ] 마켓 장바구니/구매 => 로그인 페이지로 이동


### 관리자
- [x]  전체 페이지 어드민 확인 필요

**Comment by seeoya** [comment]
관리자 페이지 로그인 제한 추가했습니다.
admin / admin1234! 
아이디로 로그인하시면 확인 가능합니다. 

@post50 @Hanbiman @choiheebeom

**Comment by post50** [comment]
회원 정보수정 페이지 로그인 체크 완료!
회원 로그인시 정상회원만 로그인하도록 수정 완료!
@seeoya @Hanbiman @choiheebeom

**Comment by post50** [comment]
로그인시 관리자 상태 999 추가

@seeoya
