### ISSUE TITLE
DB 세팅

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#4]
REST/SERVICE DB 세팅

- ERD CLOUD : https://www.erdcloud.com/d/S4ssJaNqs4x9bNS94

@Hanbiman 
추후 DB/ERD 세팅 관련사항 이 이슈 아래로 첨부해주세요.

**Comment by seeoya** [comment]
- 레시피 데이터 : REST
- 상품 데이터 : REST

- 냉장고 재료 데이터 : REST & SERVICE


service.재료 ID (냉장고) = rest.재료 ID (레시피)

ex)
[REST] 달걀프라이 레시피의 재료 요청
return 레시피(json) {
          [달걀프라이] : {
                    조리방법: { 1: "", 2: ""},
                    재료: [1, 3, 6],  id값으로 넘겨줄지
                    재료: { 1: { 이름: 달걀, id: 3번 }, 2: {이름: 소금, id: 4번 } }
          }
}

[SERVICE]
let msg = { 검색어: "감자" };




** 남은 회의 과제: 나의 냉장고에서 재료 ID 처리 어떻게 할지

cc. @Hanbiman

**Comment by seeoya** [comment]
https://github.com/seeoya/bapbaksa/commit/7826a890e41c8268e2f7a8aeb4a64718b55acaed

https://github.com/seeoya/bapbaksa/commit/5f882238563940a6e7572dc43e0134cde9fead54

**Comment by post50** [comment]
#4
AWS EC2 key -> server/lib/config/
파일 이동함.

@seeoya @Hanbiman @choiheebeom

**Comment by seeoya** [comment]
REST DB 세팅 
 https://github.com/seeoya/bapbaksa/issues/22

**Comment by seeoya** [comment]
https://github.com/seeoya/bapbaksa/blob/ec78745395ac89cbc34549f760cd5c88c95fb86d/_common/sql/bapbaksa_create.sql#L1-L112

CREATE-DROP sql

https://github.com/seeoya/bapbaksa/blob/ec78745395ac89cbc34549f760cd5c88c95fb86d/_common/sql/bapbaksa_select.sql#L1-L49

SELECT-TRUNCATE-DROP sql

작업하며 추가/수정/삭제 예정

**Comment by seeoya** [comment]
이슈 종료
테이블 수정 필요 시 신규 이슈 오픈해서 알림할 것
