### ISSUE TITLE
와이어프레임

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#5]
아래쪽으로 페이지 와이어프레임 첨부해주세요.

**Comment by seeoya** [comment]
레시피 리스트 와이어 프레임 입니다.

![image](https://github.com/seeoya/bapbaksa/assets/54855563/cbf01255-71f2-4934-8f38-f9fb280908a6)

**Comment by seeoya** [comment]
> 레시피 리스트 와이어 프레임 입니다.
> 
> ![image](https://private-user-images.githubusercontent.com/54855563/325119274-cbf01255-71f2-4934-8f38-f9fb280908a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDM1MTgsIm5iZiI6MTcxMzk0MzIxOCwicGF0aCI6Ii81NDg1NTU2My8zMjUxMTkyNzQtY2JmMDEyNTUtNzFmMi00OTM0LThmMzgtZjlmYjI4MDkwOGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA3MjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNGNhZmIwYmM2YWE4ODU1N2FkMjBlMTQzMTczZDJmNmY3NzNhMzA2NzNkMTQ2OGUzMGVmODhjNDMzNTZhN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qml_6Kcrld6Zabkv6r5JnNtKNWvFLgJ8t0NBB2fmTnU)

이 부분 수정했으니 다시 업로드하겠습니다.

**Comment by choiheebeom** [comment]
![결제 페이지](https://github.com/seeoya/bapbaksa/assets/154862080/4c974f9b-a92c-4c43-a624-151179492c67)
![구매 내역](https://github.com/seeoya/bapbaksa/assets/154862080/2befbafc-8fcb-4432-b35e-a104ea4ea960)
![레시피 리스트 냉장고 추가](https://github.com/seeoya/bapbaksa/assets/154862080/9b39b617-b8e3-4a2b-9d16-81b817ceddda)
![레시피 리스트](https://github.com/seeoya/bapbaksa/assets/154862080/4c9046d6-3c04-4b40-a73a-3dcb65d356e9)
![레시피 상세 뷰](https://github.com/seeoya/bapbaksa/assets/154862080/1cb7b611-2c0a-4cfd-b4e5-f2064bf5c8e9)
![마켓 리스트](https://github.com/seeoya/bapbaksa/assets/154862080/cf641072-4a6d-4314-a2d5-fc7eb7dd8f3a)
![장바구니](https://github.com/seeoya/bapbaksa/assets/154862080/fea36078-618c-4d37-b958-441b7b1ac199)
![재료 상세](https://github.com/seeoya/bapbaksa/assets/154862080/fe784d67-b4f9-4175-884e-37af51d74305)

마트, 레시피 와이어프레임 입니다.

**Comment by post50** [comment]
![회원_와이어프레임](https://github.com/seeoya/bapbaksa/assets/76762877/5e022f0a-44f4-498c-b8c3-b0ca97e92869)
![구매내역_좋아요리스트](https://github.com/seeoya/bapbaksa/assets/76762877/d8207636-3a32-4356-bc80-6a7b3de9ce07)


회원 / 구매내역 / 좋아요 리스트 와이어프레임

**Comment by post50** [comment]
![image](https://github.com/seeoya/bapbaksa/assets/76762877/03e9944f-1fbe-4979-97e7-d4719b3bfee6)

layout

**Comment by seeoya** [comment]
1차 종료
추후 수정사항 있을 시 재오픈
