### ISSUE TITLE
냉장고 재료 재확인

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#58]
![image](https://github.com/seeoya/bapbaksa/assets/54855563/a1d10c91-a904-4bba-876d-4f3f49b9742f)

냉장고 재료에서 레시피와 일치하지 않는 재료들 삭제 필요

드레싱, 땅콩 등...

**Comment by Hanbiman** [comment]
### 냉장고에 있으면 안되는 목록

'냉동만두'
'드레싱'
'딸기'
'땅콩'
'새우젓'
'아보카도'
'연어'
'열무'
'조기'
'체리'
