### ISSUE TITLE
TBL_USER_STATUS 테이블 변경 요청

### ISSUE THREAD

**Issue by post50** [seeoya/bapbaksa#63]
DROP TABLE IF EXISTS TBL_USER_STATUS;
CREATE TABLE TBL_USER_STATUS (
	u_status INT NOT NULL DEFAULT 1,
	u_status_name VARCHAR(30) NOT NULL
);

 INSERT INTO TBL_USER_STATUS VALUES(0, '탈퇴 회원');
 INSERT INTO TBL_USER_STATUS VALUES(1, '정상 회원');
 INSERT INTO TBL_USER_STATUS VALUES(2, '계정 정지 회원');

SELECT * FROM TBL_USER_STATUS;

@seeoya

**Comment by seeoya** [comment]
추가 완료했습니다.
