### ISSUE TITLE
메인 - 테스트 오류

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#79]
- [x] 슬라이드 loop
- [x] 레시피 메인에 링크 뭐 좀 넣어주세요 
- [x] 레시피 메인 - 하단 링크 타이틀 도트 라인 연장

**Comment by Hanbiman** [comment]
해결 완료

**Comment by seeoya** [comment]
@Hanbiman 
![image](https://github.com/seeoya/bapbaksa/assets/54855563/915c2e3d-9e09-45c5-807a-5578ce5cedbd)

마켓 슬라이더 높이 좀 줄이면 어때여

**Comment by Hanbiman** [comment]
수정 완료
