### ISSUE TITLE
테스트 케이스 작성중

### ISSUE THREAD

**Issue by seeoya** [seeoya/bapbaksa#86]
## 공통
- [x] a href 없는지 확인
- [ ] location.href 없는지 확인
- [x] 미사용 코드 제거
- [ ] console log 제거
- [ ] DB 연결
- [ ] AWS 연결
- [ ] 내역 없으면 empty 띄워줘야함
- [ ] 타이틀 다 있는지 확인
- [ ] 파비콘

## 메인
- [x] 메인 슬라이드 작동
- [x] 메인 슬라이드 필터링 정상 작동하는지
- [x] 링크 멀쩡한지

## 회원
- [x] 회원가입/정보수정 정상 작동하는지 (DB에 입력되는지)
- [x] 회원가입/로그인 유효성/정보수정 유효성 체크(빈값)
- [x] 회원가입 아이디 중복 검사
- [x] 정보수정 아이디 수정 안 되는지
- [x] 프로필 사진 추가/수정 되는지
- [x] 주소 입력 정상작동하는지
- [x] 아이디/PW 찾기 문자/이메일 정상 작동하는지
- [x] 로그인/로그아웃 정상 작동하는지 (로컬 스토리지 확인)
- [ ] 탈퇴 시 정보 다 삭제 잘 되는지 (개인정보, 마이페이지, 구매 관련 / 결제 내역, 구매 내역은 남아있어야 함)
- [ ] 탈퇴 시 아이디 변경 되는지

## 마이페이지
- [x] 좋아하는 레시피 잘 뜨는지
- [x] 좋아하는 레시피 추가 제거 잘 되는지
- [x] 내 냉장고 잘 뜨는지 ~ 레시피 리스트/상세뷰에서도 연동 되는지
- [x] 내 냉장고 추가/제거 잘 되는지
- [ ] 결제 내역 잘 나오는지
- [ ] 1:1 문의 내역
- [ ] 1:1 문의 등록

## 레시피
- [x] 레시피 리스트 잘 뜨는지
- [x] 필터링 잘 되는지 & 동시에 잘 되는지 (검색/재료/리전/카테고리/난이도)
- [x] 검색 잘 되는지
- [x] 상세 페이지 잘 보이는지
- [x] 북마크 추가/제거 잘 되는지
- [x] 재료 잘 나오는지
- [x] 재료 클릭하면 마켓으로 이동 잘 되는지(검색까지)

## 마켓
- [x] 리스트 잘 뜨는지
- [x] 검색/카테고리 필터링 잘 되는지 (동시에 되는지)
- [x] 상세 페이지 잘 들어가지는지
- [x] 상세 페이지에서 수량 0개 미만으로 안 떨어지는지
- [x] 상세 페이지에서 장바구니에 잘 담기는지 / 수량 체크
- [x] 상세 페이지에서 선택 결제 페이지 이동 잘 되는지 / 수량 체크
- [x] 상세 페이지에서 품절 체크 되고 있는지 > 장바구니나 선택 결제로 넘어갈 때 품절 처리 되는지
- [x] 장바구니에서 수량 변경 되는지
- [x] 장바구니에서 선택한 아이템만 결제창으로 넘어가는지
- [x] 결제 페이지에서 값 잘 넘어오는지
- [x] 결제 페이지에서 회원 정보에 있는 주소 잘 나오는지
- [x] 회원 정보와 다른 주소 입력했을 때 결제 후 주소 잘 바뀌어서 나오는지
- [x] 결제 버튼 눌렀을 때 -1로 구매 내역에 입력 잘 되는지
- [x] 테스트 결제 잘 되는지 (tosspayments)
- [x] 결제 승인 후 결제 테이블에 등록 잘 되는지
- [ ] 구매 내역에 내역 잘 뜨는지
- [ ] 구매내역 - 구매 취소
- [ ] 구매내역 - 환불 신청
- [ ] 구매내역 - 구매 확정

## 관리자
- [x] 회원목록
- [x] 회원정보수정
- [ ] 1:1 문의 내역
- [ ] 1:1 문의 답변
- [ ] 구매내역 상태 확인
- [ ] 환불 내역
- [ ] 환불 승인
- [ ] 환불 거절
- [ ] 재고관리 추가삭제
- [ ] 재고관리 확인

**Comment by seeoya** [comment]
AWS 업로드 전 확인

## 공통
- [ ] a href 없는지 확인
- [ ] 미사용 코드 제거
- [x] console log 제거
- [ ] DB 연결
- [ ] AWS 연결
- [ ] 내역 없으면 empty 띄워줘야함
- [ ] 타이틀 다 있는지 확인
- [x] 파비콘


## 메인
- [x] 메인 슬라이드 작동
- [x] 메인 슬라이드 필터링 정상 작동하는지
- [x] 링크 멀쩡한지


## 회원
- [x] 회원가입/정보수정 정상 작동하는지 (DB에 입력되는지)
- [ ] 회원가입/로그인 유효성/정보수정 유효성 체크(빈값)
- [x] 회원가입 아이디 중복 검사
- [x] 정보수정 아이디 수정 안 되는지
- [x] 프로필 사진 추가/수정 되는지
- [x] 주소 입력 정상작동하는지
- [x] 아이디/PW 찾기 문자/이메일 정상 작동하는지
- [x] 로그인/로그아웃 정상 작동하는지 (로컬 스토리지 확인)
- [ ] 탈퇴 시 정보 다 삭제 잘 되는지 (개인정보, 마이페이지, 구매 관련 / 결제 내역, 구매 내역은 남아있어야 함)
- [x] 탈퇴 시 아이디 변경 되는지


## 마이페이지
- [x] 좋아하는 레시피 잘 뜨는지
- [x] 좋아하는 레시피 추가 제거 잘 되는지
- [x] 내 냉장고 잘 뜨는지 ~ 레시피 리스트/상세뷰에서도 연동 되는지
- [x] 내 냉장고 추가/제거 잘 되는지
- [x] 결제 내역 잘 나오는지
- [x] 1:1 문의 내역
- [x] 1:1 문의 등록

## 레시피
- [x] 레시피 리스트 잘 뜨는지
- [x] 필터링 잘 되는지 & 동시에 잘 되는지 (검색/재료/리전/카테고리/난이도)
- [x] 검색 잘 되는지
- [x] 상세 페이지 잘 보이는지
- [x] 북마크 추가/제거 잘 되는지
- [x] 재료 잘 나오는지
- [x] 재료 클릭하면 마켓으로 이동 잘 되는지(검색까지)


## 마켓
- [x] 리스트 잘 뜨는지
- [x] 검색/카테고리 필터링 잘 되는지 (동시에 되는지)
- [x] 상세 페이지 잘 들어가지는지
- [x] 상세 페이지에서 수량 0개 미만으로 안 떨어지는지
- [x] 상세 페이지에서 장바구니에 잘 담기는지 / 수량 체크
- [ ] 상세 페이지에서 선택 결제 페이지 이동 잘 되는지 / 수량 체크
- [ ] 상세 페이지에서 품절 체크 되고 있는지 > 장바구니나 선택 결제로 넘어갈 때 품절 처리 되는지
- [x] 장바구니에서 수량 변경 되는지
- [x] 장바구니에서 선택한 아이템만 결제창으로 넘어가는지
- [x] 결제 페이지에서 값 잘 넘어오는지
- [x] 결제 페이지에서 회원 정보에 있는 주소 잘 나오는지
- [x] 회원 정보와 다른 주소 입력했을 때 결제 후 주소 잘 바뀌어서 나오는지
- [x] 결제 버튼 눌렀을 때 -1로 구매 내역에 입력 잘 되는지
- [x] 테스트 결제 잘 되는지 (tosspayments)
- [x] 결제 승인 후 결제 테이블에 등록 잘 되는지
- [x] 구매 내역에 내역 잘 뜨는지
- [x] 구매내역 - 구매 취소
- [x] 구매내역 - 환불 신청
- [x] 구매내역 - 구매 확정


## 관리자
- [x] 회원목록
- [x] 회원정보수정
- [x] 1:1 문의 내역
- [x] 1:1 문의 답변
- [ ] 구매내역 상태 확인
- [x] 환불 내역
- [x] 환불 승인
- [x] 환불 거절
- [x] 재고관리 추가삭제
- [x] 재고관리 확인

**Comment by choiheebeom** [comment]
- [ ]  회원가입 시 중복체크 후 아이디값 바꿨을 때 중복체크 안 해도 회원가입 가능

- [ ] 정보수정 비밀번호 변경 시 비밀번호 확인 쪽 상태 체크

- [ ] 회원탈퇴 시 내 냉장고, 좋아요 레시피, 장바구니가 DB에서 안 날라감

- [ ] 회원탈퇴 시 로컬스토리지가 안 비워짐

- [ ] 마이페이지에서 구매내역에서 고객문의로 갈 때 링크가 잘못 돼서 존재하지 않는 페이지

- [x] 마켓 상페 페이지 수량 인풋 css 수정

- [x] 마켓 상세 페이지에서 선택 결제 이동 시 수량 1로 고정

- [x] 관리자에서 품절 처리 하고 마켓 상세 페이지에서 결제, 장바구니가 넘어감

- [ ] 어드민 결제 내역에서 결제 대기 중도 나옴

- [ ] 어드민 환불 승인 거절 시 DB는 바뀌는데 상세 내역 구매상태가 안 바뀜 

- [ ] 나의 냉장고에 재료가 없을 시 로그인 후 확인할 수 있습니다. [ 문구 변경 ]
- [ ] 1:1 문의 주문 번호 선택이 품목 수만큼 나옴

**Comment by seeoya** [comment]
- [x] 결제 내역 없을 때 없다고 적어두기
